Repository python/typing, pull requests merged in 2021-11, with the labels that each got.

#917 Upgrade Sphinx
  docs/requirements.txt
Labels: CLA signed

#916 Move individual pages from toplevel docs
  docs/README.rst
  docs/index.rst
  docs/source/libraries.rst
  docs/source/stubs.rst
Labels: CLA signed

#918 Fix link in README
  docs/README.rst
Labels: CLA signed

#907 Use Semantic Versioning for typing_extensions
  CONTRIBUTING.md
  typing_extensions/CHANGELOG
  typing_extensions/MANIFEST.in
  typing_extensions/README.rst
  typing_extensions/setup.cfg
  typing_extensions/setup.py
Labels: CLA signed

#931 Clean-up `typing_extensions` -- meta
  .flake8
  .flake8-tests
  CONTRIBUTING.md
  test-requirements.txt
  typing_extensions/README.rst
  typing_extensions/pyproject.toml
  typing_extensions/setup.cfg
  typing_extensions/setup.py
Labels: CLA signed

#932 Clean-up `typing_extensions` -- `typing_extensions`
  typing_extensions/CHANGELOG
  typing_extensions/src_py3/test_typing_extensions.py
  typing_extensions/src_py3/typing_extensions.py
Labels: CLA signed

#935 Use unittest for testing instead of pytest
  .github/workflows/ci.yml
  test-requirements.txt
Labels: CLA signed

#933 Add PEP 673 Self type
  typing_extensions/CHANGELOG
  typing_extensions/src_py3/test_typing_extensions.py
  typing_extensions/src_py3/typing_extensions.py
Labels: CLA signed

#934 Make library guidelines checker agnostic
  docs/source/libraries.rst
Labels: CLA signed

#937 PEP 655 support redux
  typing_extensions/CHANGELOG
  typing_extensions/README.rst
  typing_extensions/src_py3/test_typing_extensions.py
  typing_extensions/src_py3/typing_extensions.py
Labels: CLA signed, topic: typing-extensions

#921 Create issue templates
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/new-typing-feature.md
  .github/ISSUE_TEMPLATE/other-issue.md
  .github/ISSUE_TEMPLATE/typing-extensions-issue.md
Labels: CLA signed, topic: maintenance

#941 prepare release 4.0.0
  typing_extensions/CHANGELOG
  typing_extensions/pyproject.toml
Labels: CLA signed

#942 Add `Self` type to the README of typing-extensions
  typing_extensions/README.rst
Labels: CLA signed

#949 Documentation: Add links to typing PEPs
  docs/index.rst
Labels: CLA signed, topic: documentation

#951 Update typing-extensions README
  typing_extensions/README.rst
Labels: CLA signed

#952 Link fixes
  docs/index.rst
Labels: CLA signed

#965 Rename src_py3 to src
  .flake8
  .github/workflows/ci.yml
  .github/workflows/package.yml
  CONTRIBUTING.md
  typing_extensions/MANIFEST.in
  typing_extensions/pyproject.toml
  typing_extensions/src/test_typing_extensions.py
  typing_extensions/src/typing_extensions.py
  typing_extensions/tox.ini
Labels: CLA signed

#967 Link to English version of Pycharm's landing site in index
  docs/index.rst
Labels: CLA signed

#969 prepare changelog
  typing_extensions/CHANGELOG
Labels: CLA signed

#966 Vendor typing._SpecialForm to fool typing._type_check
  typing_extensions/src/test_typing_extensions.py
  typing_extensions/src/typing_extensions.py
Labels: CLA signed
